# Generated by Django 3.1.3 on 2020-11-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('value_default', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
            ],
        ),
    ]
